r15 : input.r15,
r14 : input.r14,
r13 : input.r13,
r12 : input.r12,
rbp : input.rbp,
rbx : input.rbx,

r11 : input.r11,
r10 : input.r10,
r9 : input.r9,
r8 : input.r8,
rax : input.rax,
rcx : input.rcx,
rdx : input.rdx,
rsi : input.rsi,
rdi : input.rdi,

orig_ax : input.orig_ax,

rip : input.rip,
rcs : input.rcs,
rflags : input.rflags,
rsp : input.rsp,
ss : input.ss,