[package]
name = "pcid"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.0"
byteorder = { version = "1.2", default-features = false }
serde_derive = "1.0.101"
heapless = "0.7.16"
log = "0.4.19"
