[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astd = { path = "../../astd" }
asys = { path = "../../asys" }
log = "0.4.19"
