// pub mod syscall_receive;
// pub mod syscall_reply;
pub mod syscall_reply_empty;
pub mod syscall_reply_message;
pub mod syscall_reply_and_receive;
// pub mod syscall_call_with_message;
// pub mod syscall_send;
// pub mod syscall_send_empty;
// pub mod syscall_send_empty_no_wait;
// pub mod syscall_send_message;
// pub mod syscall_send_pages;
// pub mod syscall_send_endpoint;
// pub mod syscall_receive_empty;
// pub mod syscall_receive_message;
// pub mod syscall_receive_pages;
// pub mod syscall_receive_endpoint;

// pub use syscall_receive::*;
// pub use syscall_reply::*;
pub use syscall_reply_empty::*;
pub use syscall_reply_message::*;
pub use syscall_reply_and_receive::*;
// pub use syscall_call_with_message::*;
// pub use syscall_send::*;
// pub use syscall_send_empty::*;
// pub use syscall_send_empty_no_wait::*;
// pub use syscall_send_message::*;
// pub use syscall_send_pages::*;
// pub use syscall_send_endpoint::*;
// pub use syscall_receive_empty::*;
// pub use syscall_receive_message::*;
// pub use syscall_receive_pages::*;
// pub use syscall_receive_endpoint::*;
