[package]
name = "astd"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
atomic_refcell = "0.1.10"
displaydoc = { version = "0.2.4", default-features = false }
embedded-io = "0.5.0"
heapless = "0.7.16"
spin = "0.9.8"
